import "./globals.css";
import Navbar from "./components/navbar/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={{ backgroundImage: "linear-gradient(to right bottom, #37393d, #303134, #29292b, #222223, #1b1b1b)", backgroundRepeat: "no-repeat", backgroundAttachment: "fixed", backgroundSize: "cover", backgroundPosition: "center" }}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
